use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};
use thiserror::Error;
use tracing::info;

#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("Postgres data directory {0} does not exist")]
    MissingDataDir(PathBuf),
}

/// Postgres instance configuration parameters.
#[derive(Debug, Clone)]
pub struct PostgresConfig {
    pub port: u16,
    pub max_connections: u32,
    pub shared_buffers: String,
    pub wal_keep_size: String,
    pub archive_command: Option<String>,
    pub primary_conninfo: Option<String>,
}

impl Default for PostgresConfig {
    fn default() -> Self {
        Self {
            port: 5432,
            max_connections: 100,
            shared_buffers: "128MB".to_string(),
            wal_keep_size: "1GB".to_string(),
            archive_command: None,
            primary_conninfo: None,
        }
    }
}

/// Configuration generator for PostgreSQL instance data directory.
pub struct ConfigGenerator;

impl ConfigGenerator {
    /// Writes customized `postgresql.conf` and `pg_hba.conf` into data directory.
    pub fn write_configs(
        data_dir: impl AsRef<Path>,
        config: &PostgresConfig,
    ) -> Result<(), ConfigError> {
        let dir = data_dir.as_ref();
        if !dir.exists() {
            fs::create_dir_all(dir)?;
        }

        // 1. Write postgresql.conf
        let conf_path = dir.join("postgresql.conf");
        let mut conf_content = format!(
            "# Generated by pgvisor-sidecar\n\
            listen_addresses = '*'\n\
            port = {port}\n\
            max_connections = {max_conn}\n\
            shared_buffers = {buffers}\n\
            wal_level = replica\n\
            max_wal_senders = 10\n\
            wal_keep_size = '{wal_size}'\n\
            hot_standby = on\n",
            port = config.port,
            max_conn = config.max_connections,
            buffers = config.shared_buffers,
            wal_size = config.wal_keep_size
        );

        if let Some(archive_cmd) = &config.archive_command {
            conf_content.push_str(&format!(
                "archive_mode = on\n\
                archive_command = '{archive_cmd}'\n"
            ));
        }

        if let Some(primary_info) = &config.primary_conninfo {
            conf_content.push_str(&format!("primary_conninfo = '{primary_info}'\n"));
            // Standby indicator file
            let standby_signal = dir.join("standby.signal");
            File::create(standby_signal)?;
            info!("Created standby.signal for replica instance");
        } else {
            // Remove standby.signal if promoting or running as primary
            let standby_signal = dir.join("standby.signal");
            if standby_signal.exists() {
                let _ = fs::remove_file(standby_signal);
            }
        }

        let mut conf_file = File::create(&conf_path)?;
        conf_file.write_all(conf_content.as_bytes())?;
        conf_file.sync_all()?;

        // 2. Write pg_hba.conf
        let hba_path = dir.join("pg_hba.conf");
        let hba_content = "\
            # Generated by pgvisor-sidecar\n\
            # TYPE  DATABASE        USER            ADDRESS                 METHOD\n\
            local   all             all                                     trust\n\
            host    all             all             127.0.0.1/32            trust\n\
            host    all             all             ::1/128                 trust\n\
            host    all             all             all                     trust\n\
            host    replication     all             all                     trust\n";

        let mut hba_file = File::create(&hba_path)?;
        hba_file.write_all(hba_content.as_bytes())?;
        hba_file.sync_all()?;

        info!(path = ?conf_path, "PostgreSQL configurations written successfully");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_write_primary_config() {
        let dir = tempdir().unwrap();
        let config = PostgresConfig {
            port: 5432,
            archive_command: Some("test_archive %p %f".into()),
            ..Default::default()
        };

        ConfigGenerator::write_configs(dir.path(), &config).unwrap();
        let conf = fs::read_to_string(dir.path().join("postgresql.conf")).unwrap();
        assert!(conf.contains("port = 5432"));
        assert!(conf.contains("archive_mode = on"));
        assert!(!dir.path().join("standby.signal").exists());
    }

    #[test]
    fn test_write_standby_config() {
        let dir = tempdir().unwrap();
        let config = PostgresConfig {
            port: 5433,
            primary_conninfo: Some("host=127.0.0.1 port=5432 user=postgres".into()),
            ..Default::default()
        };

        ConfigGenerator::write_configs(dir.path(), &config).unwrap();
        let conf = fs::read_to_string(dir.path().join("postgresql.conf")).unwrap();
        assert!(conf.contains("primary_conninfo = 'host=127.0.0.1 port=5432 user=postgres'"));
        assert!(dir.path().join("standby.signal").exists());
    }
}
