[package]
name = "pgvisor-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
byteorder = { workspace = true }
crc32fast = { workspace = true }
openraft = { workspace = true }
tokio-util = { workspace = true }
opendal = { workspace = true }
chrono = { workspace = true }
pgwire = { workspace = true }

[dev-dependencies]
tempfile = "3.12"
